# Generated by Django 2.2 on 2019-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='beijing', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.TextField(default='kk', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.BigIntegerField(default=110),
            preserve_default=False,
        ),
    ]
